version: "3"
services:

  #
  # InfluxDB
  #

  influxdb:
    image: "influxdb:1.8.5"
    ports:
      - "8086:8086"
    volumes:
      - "./config/influxdb.conf:/etc/influxdb/infux.conf:ro"
      - "influx_data:/var/lib/influxdb"

volumes:
  influx_data:

