version: "3"
services:

  #
  # InfluxDB
  #

  influxdb:
    image: "influxdb:2.0.6-alpine"
    ports:
      - "8086:8086"
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=aleisium_app"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=password"
      - "DOCKER_INFLUXDB_INIT_ORG=aleisium"
      - "DOCKER_INFLUXDB_INIT_BUCKET=aleisium"
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=devtoken"
    volumes:
      - type: "volume"
        source: "influx_config"
        target: "/etc/influxdb2"
      - type: "volume"
        source: "influx_data"
        target: "/var/lib/influxdb2"

volumes:
  influx_config:
  influx_data:

