version: "3"
services:

  #
  # SensorReader
  #

  sensorreader:
    build:
      context: "."
    networks:
      - "weather0"
    restart: "always"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"

networks:
  weather0:
    external: true
    name: weather0

