version: "3"
services:

  #
  # SensorReader
  #

  sensorreader:
    image: "aleisium/sensor-reader:latest"
    networks:
      - "weather0"
    restart: "always"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"

networks:
  weather0:
    external: true
    name: weather0

