version: "3"
services:

  #
  # SensorReader
  #

  sensorreader:
    environment:
      - "WEATHER_STATION_ID=hea92weather01"
      - "BROKER_USERNAME=hea92weather01"
      - "BROKER_PASSWORD=password"
      - "SAMPLE_INTERVAL=15"
    image: "aleisium/sensor-reader:latest"
    networks:
      - "weather0"
    restart: "always"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"

networks:
  weather0:
    external: true
    name: weather0

