version: "3"
services:

  mosquitto:
    image: "eclipse-mosquitto:2.0.10"
    networks:
      - "weather0"
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: "always"
    volumes:
      - "./config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./config/users:/mosquitto/config/users"
      - "mosquitto-data:/mosquitto/data/"
      - "mosquitto-logs:/mosquitto/log/"

networks:
  weather0:
    external: true
    name: weather0

volumes:
  mosquitto-data:
  mosquitto-logs:
