version: "3"
services:

  #
  # InfluxDB
  #

  influxdb:
    image: "influxdb:1.8.5"
    networks:
      - "weather0"
    ports:
      - "8086:8086"
    restart: "always"
    volumes:
      - "./config/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
      - "influx_data:/var/lib/influxdb"

  telegraf:
    image: "telegraf:1.18.2"
    networks:
      - "weather0"
    restart: "always"
    volumes:
      - "./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro"

networks:
  weather0:
    external: true
    name: weather0

volumes:
  influx_data:

